// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire gen -tags "wireinjection"
//go:build !wireinject
// +build !wireinject

package wire

import (
	"PetTrack/infra/00-core/model"
)

// Injectors from wire.go:

func InitService(cfg model.Config) (*Services, error) {
	db := provideDB(cfg)
	passwordRepository := providePasswordRepo(db)
	accountRepository := provideAccountRepo(db)
	memberRepository := provideMemberRepo(db)
	accountService := provideAccountService(db, passwordRepository, accountRepository, memberRepository)
	deviceRepository := provideDeviceRepo(db)
	database := provideMongo(cfg)
	tripRepository := provideTripRepo(db, database)
	client := provideRedis(cfg)
	redisRepository := provideRedisRepo(client)
	redisService := provideRedisService(redisRepository, client)
	deviceService := provideDeviceService(deviceRepository, tripRepository, redisService)
	memberDeviceRepository := provideMemberDeviceRepo(db)
	memberService := provideMemberService(deviceRepository, memberDeviceRepository)
	commonService := provideCommonService(deviceRepository, memberDeviceRepository)
	tripService := provideTripService(tripRepository, commonService, redisRepository)
	services := InitServices(accountService, deviceService, memberService, commonService, redisService, tripService)
	return services, nil
}
